# Generated by Django 3.1.6 on 2021-02-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllToiletNum',
            fields=[
                ('location', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('toilet_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_toilet_num',
                'managed': False,
            },
        ),
    ]
